apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ewec6vrn1-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ewec6vrn1-java-quarkus-gitops